authors:
  sunish:
    name: Sunish Bharathan
    description: Technical Program Manager - Engineering Delivery and AI Systems
    avatar: https://avatars.githubusercontent.com/sunishbharat
    url: https://linkedin.com/in/sunishbharathan
