name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies for imaging
        run: sudo apt-get install -y libcairo2 libfreetype6 libffi-dev libjpeg-dev libpng-dev zlib1g pngquant

      - name: Install MkDocs Material
        run: pip install "mkdocs-material[imaging]"

      - name: Deploy
        run: mkdocs gh-deploy --force
